name: Build
on: [push, pull_request]
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
        experimental: [false]
        include:
        - node: 21.x
          experimental: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js (NPMJS) ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build:ci
